Controllers/EmployeeController.cs
using PopUp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PopUp.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        private ApplicationDbContext _db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData()
        {
            List<Employee> employeeList = _db.Employees.ToList<Employee>();
            return Json(new { data = employeeList }, JsonRequestBehavior.AllowGet);

        } 
        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
            if (id == 0)
            {
                return View(new Employee());
            }
              
            else
            {
                return View(_db.Employees.Where(x=>x.EmployeeId==id).FirstOrDefault<Employee>());
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(Employee emp)
        {
            if (emp.EmployeeId == 0)
            {
                _db.Employees.Add(emp);
                _db.SaveChanges();
                return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                _db.Entry(emp).State = EntityState.Modified;
                _db.SaveChanges();
                return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id=0)
        {
            if(id==0)
                return Json(new { success = true, message = " Not Deleted" }, JsonRequestBehavior.AllowGet);

            var empDetails = _db.Employees.Find(id);
            _db.Employees.Remove(empDetails);
            _db.SaveChanges();

            return Json(new { success=true, message="Deleted Successfully"}, JsonRequestBehavior.AllowGet);
        }

       
        public JsonResult GetSearchList(string search)
        {
            ApplicationDbContext _db = new ApplicationDbContext();
            List<ProductModel> allsearch = _db.Employees.Where(x => x.Name.Contains(search)).Select(x => new ProductModel
            {
                Id = x.EmployeeId,
                Name = x.Name
            }).ToList();
            return new JsonResult { Data = allsearch, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        public class ProductModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
    }
}

Controllers/ListInBootstrapModalController.cs
using PopUp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PopUp.Controllers
{
    public class ListInBootstrapModalController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        // GET: ListInBootstrapModal
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetData()
        {
            List<Employee> employeeList = _db.Employees.ToList<Employee>();
            return Json(new { data = employeeList }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Details(int id)
        {
            List<Employee> employeeList = _db.Employees.Where(w=>w.EmployeeId==id).ToList();
            return PartialView("_Details", employeeList);
        }
    }
}

Views/ListInBootstrapModal/Index.cshtml
@{
    ViewBag.Title = "EmployeeList";
}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div id='myModalContent'></div>
</div>


<h2>Employee CRUD Operation</h2>
<a class="btn btn-success" style="margin-bottom:10px;" onclick="Popupform('@Url.Action("AddOrEdit","Employee")')"><i class="fa fa-plus"></i> Add New</a>
<table id="employeeTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Age</th>
            <th>Salary</th>
            <th></th>

        </tr>
    </thead>
</table>



@section scripts{



    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script>
        var Popup, dataTable;
        $(document).ready(function () {
            dataTable= $("#employeeTable").DataTable({
                "ajax": {
                    "url": "/Employee/GetData",
                    "type": "GET",
                    "dataType": "json"

                },
                "columns": [
                    { "data": "Name" },
                    { "data": "Position" },
                    { "data": "Office" },
                    { "data": "Age" },
                    { "data": "Salary" },
                    { "data": "EmployeeId", "render": function (data) {
                        return "<a class='btn btn-primary btn-sm' onclick=Popupform('@Url.Action("Details", "ListInBootstrapModal")/"+ data +"')><i class='fa fa-pencil'></i> Details</a>"
                    },
                        "orderable": false,
                        "searchable": false,
                        "width":"150px"
                    }
                ],
                "language": {
                    "emptyTable": "No data found, please click on <b>Add New</b> button"
                }
            });

        });

        //function Popupform(url) {
        //    var formDiv = $('<div/>');
        //    $.get(url)
        //        .done(function (response) {
        //            formDiv.html(response);

        //            Popup = formDiv.dialog({
        //                autoOpen: true,
        //                resizable: false,
        //                title: 'Fill Employee Details',
        //                height: 600,
        //                width: 700,
        //                close: function () {
        //                    Popup.dialog('destory').remove();
        //                }

        //            });

        //        });
        //}



        function Popupform(url) {
            var options = { "backdrop": "static", keyboard: true };
            $.ajax({
                type: "GET",
                url: url,
                contentType: "application/json; charset=utf-8",
             //   data: { "Id": id },
                datatype: "json",
                success: function (data) {
                    debugger;
                    $('#myModalContent').html(data);
                    $('#myModal').modal(options);
                    $('#myModal').modal('show');

                },
                error: function () {
                    alert("Dynamic content load failed.");
                }
            });
            return false;
        }
    </script>
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>


<link href="~/Content/themes/base/autocomplete.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

<div>
    <label>Country Search</label>
    <input class="form-control" id="searchInput" />
</div>
<script>
    $("#searchInput").autocomplete({
        source: function (request, response) {
            $.ajax({
                url: '@Url.Action("GetSearchList", "Employee")',
                dataType: "json",
                data: { search: $("#searchInput").val() },
                success: function (data) {
                    response(data);
                },
                error: function (xhr, status, error) {
                    alert("Error");
                }
            });
        }
    }).autocomplete('instance')._renderItem = function (ul, item) {
        return $('<li>')
            //.append("<img class='imageClass' src=" + item.Name + " alt=" + item.Name + "/>")
            .append('<a href="/Home/Index">' + item.Name + '</a>')
            .appendTo(ul);
    };

    //function updateTextBox(event, ui) {
    //    $(this).val(ui.item.Name);
    //    return false;
    //}

    @*$(document).ready(function () {
        $('#searchInput').autocomplete({
            minLength: 1,
            source: function (request, response) {
                $.ajax({
                    url: '@Url.Action("GetSearchList", "ProductSearch")',
                    method: 'post',
                    data: { term: request.term },
                    dataType: 'json',
                    success: function (data) {
                        response(data);
                    },
                    error: function (err) {
                        alert(err);
                    }
                });
            },
            focus: updateTextBox,
            select: updateTextBox
        })
            .autocomplete('instance')._renderItem = function (ul, item) {
                return $('<li>')
                    .append("<img class='imageClass' src=" + item.FlagPath + " alt=" + item.Name + "/>")
                    .append('<a>' + item.Name + '</a>')
                    .appendTo(ul);
            };

        function updateTextBox(event, ui) {
            $(this).val(ui.item.Name);
            return false;
        }
    });*@
</script>

Views/ListInBootstrapModal/_Details.cshtml
@*@model IEnumerable<PopUp.Models.Employee>*@


<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
             @foreach(var item in Model)
             {
                 <p>@item.Name</p>
             }
        </div>
    </div>
</div>